services:
  latex-template:
    image: latex/template:1.0
    build: .
    container_name: latex-template
    working_dir: /latex-template/tex
    volumes:
    - ../:/latex-template
    command: latexmk -pdf -shell-escape -outdir=out main.tex